version: "3"
services:
  app:
    container_name: app
    image: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/usr/src/app/demo
      - ./dialogue_agent_data:/usr/src/app/data
